[package]
name = "themelio-bootstrap"
version = "0.6.1"
edition = "2018"
description="Trust bootstrapping for Themelio clients"
license = "ISC"
authors = ["nullchinchilla <nullchinchilla@pm.me>", "Themelio Labs"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
themelio-nodeprot = "0.12.0"
themelio-structs = "0.2"
